[tool.isort]
profile = "black"
known_first_party = ["app"]  # ← src → app
skip = ["tests"]

[tool.black]
line-length = 88
target-version = ['py311']
exclude = '''
/(
    \.git
  | \.venv
  | tests
)/
'''
